// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fortress/fortress.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Fortress struct {
	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount     string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee        string `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
	Collateral string `protobuf:"bytes,4,opt,name=collateral,proto3" json:"collateral,omitempty"`
	Deadline   string `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	State      string `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Borrower   string `protobuf:"bytes,7,opt,name=borrower,proto3" json:"borrower,omitempty"`
	Lender     string `protobuf:"bytes,8,opt,name=lender,proto3" json:"lender,omitempty"`
}

func (m *Fortress) Reset()         { *m = Fortress{} }
func (m *Fortress) String() string { return proto.CompactTextString(m) }
func (*Fortress) ProtoMessage()    {}
func (*Fortress) Descriptor() ([]byte, []int) {
	return fileDescriptor_d949d867b0ff5f59, []int{0}
}
func (m *Fortress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fortress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fortress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fortress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fortress.Merge(m, src)
}
func (m *Fortress) XXX_Size() int {
	return m.Size()
}
func (m *Fortress) XXX_DiscardUnknown() {
	xxx_messageInfo_Fortress.DiscardUnknown(m)
}

var xxx_messageInfo_Fortress proto.InternalMessageInfo

func (m *Fortress) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Fortress) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Fortress) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *Fortress) GetCollateral() string {
	if m != nil {
		return m.Collateral
	}
	return ""
}

func (m *Fortress) GetDeadline() string {
	if m != nil {
		return m.Deadline
	}
	return ""
}

func (m *Fortress) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Fortress) GetBorrower() string {
	if m != nil {
		return m.Borrower
	}
	return ""
}

func (m *Fortress) GetLender() string {
	if m != nil {
		return m.Lender
	}
	return ""
}

func init() {
	proto.RegisterType((*Fortress)(nil), "Karan3108.fortress.fortress.Fortress")
}

func init() { proto.RegisterFile("fortress/fortress.proto", fileDescriptor_d949d867b0ff5f59) }

var fileDescriptor_d949d867b0ff5f59 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xb3, 0x69, 0x1b, 0xe3, 0x1c, 0x44, 0x16, 0xd1, 0x45, 0x61, 0x29, 0x9e, 0x7a, 0x31,
	0xab, 0xf4, 0xe2, 0xd9, 0x83, 0x20, 0xde, 0x7a, 0xf4, 0xb6, 0xe9, 0x4e, 0x35, 0xb0, 0xcd, 0x96,
	0xc9, 0x16, 0xf5, 0x2d, 0x7c, 0x2c, 0xf1, 0xd4, 0xa3, 0x47, 0x49, 0x5e, 0x44, 0xb2, 0x69, 0x42,
	0x6f, 0xff, 0x37, 0x3f, 0x03, 0x33, 0x1f, 0x5c, 0xac, 0x1c, 0x79, 0xc2, 0xaa, 0x52, 0x7d, 0xc8,
	0x36, 0xe4, 0xbc, 0xe3, 0x57, 0xcf, 0x9a, 0x74, 0x39, 0xbf, 0xbb, 0xbd, 0xcf, 0x86, 0xa6, 0x0f,
	0xd7, 0x3f, 0x0c, 0xd2, 0xc7, 0x3d, 0xf0, 0x13, 0x88, 0x0b, 0x23, 0xd8, 0x94, 0xcd, 0xc6, 0x8b,
	0xb8, 0x30, 0xfc, 0x1c, 0x12, 0xbd, 0x76, 0xdb, 0xd2, 0x8b, 0x78, 0xca, 0x66, 0xc7, 0x8b, 0x3d,
	0xf1, 0x53, 0x18, 0xad, 0x10, 0xc5, 0x28, 0x0c, 0xdb, 0xc8, 0x25, 0xc0, 0xd2, 0x59, 0xab, 0x3d,
	0x92, 0xb6, 0x62, 0x1c, 0x8a, 0x83, 0x09, 0xbf, 0x84, 0xd4, 0xa0, 0x36, 0xb6, 0x28, 0x51, 0x4c,
	0x42, 0x3b, 0x30, 0x3f, 0x83, 0x49, 0xe5, 0xb5, 0x47, 0x91, 0x84, 0xa2, 0x83, 0x76, 0x23, 0x77,
	0x44, 0xee, 0x1d, 0x49, 0x1c, 0x75, 0x1b, 0x3d, 0xb7, 0x77, 0x59, 0x2c, 0x0d, 0x92, 0x48, 0xbb,
	0xbb, 0x3a, 0x7a, 0x78, 0xfa, 0xae, 0x25, 0xdb, 0xd5, 0x92, 0xfd, 0xd5, 0x92, 0x7d, 0x35, 0x32,
	0xda, 0x35, 0x32, 0xfa, 0x6d, 0x64, 0xf4, 0xa2, 0x5e, 0x0b, 0xff, 0xb6, 0xcd, 0xb3, 0xa5, 0x5b,
	0xab, 0xa0, 0xe3, 0xa6, 0xf5, 0xa1, 0xfa, 0xcf, 0xd5, 0xc7, 0x20, 0x4d, 0xf9, 0xcf, 0x0d, 0x56,
	0x79, 0x12, 0xdc, 0xcd, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x26, 0x4e, 0x1e, 0x55, 0x56, 0x01,
	0x00, 0x00,
}

func (m *Fortress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fortress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fortress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Lender) > 0 {
		i -= len(m.Lender)
		copy(dAtA[i:], m.Lender)
		i = encodeVarintFortress(dAtA, i, uint64(len(m.Lender)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Borrower) > 0 {
		i -= len(m.Borrower)
		copy(dAtA[i:], m.Borrower)
		i = encodeVarintFortress(dAtA, i, uint64(len(m.Borrower)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintFortress(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Deadline) > 0 {
		i -= len(m.Deadline)
		copy(dAtA[i:], m.Deadline)
		i = encodeVarintFortress(dAtA, i, uint64(len(m.Deadline)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Collateral) > 0 {
		i -= len(m.Collateral)
		copy(dAtA[i:], m.Collateral)
		i = encodeVarintFortress(dAtA, i, uint64(len(m.Collateral)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintFortress(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintFortress(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintFortress(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintFortress(dAtA []byte, offset int, v uint64) int {
	offset -= sovFortress(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Fortress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovFortress(uint64(m.Id))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovFortress(uint64(l))
	}
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovFortress(uint64(l))
	}
	l = len(m.Collateral)
	if l > 0 {
		n += 1 + l + sovFortress(uint64(l))
	}
	l = len(m.Deadline)
	if l > 0 {
		n += 1 + l + sovFortress(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovFortress(uint64(l))
	}
	l = len(m.Borrower)
	if l > 0 {
		n += 1 + l + sovFortress(uint64(l))
	}
	l = len(m.Lender)
	if l > 0 {
		n += 1 + l + sovFortress(uint64(l))
	}
	return n
}

func sovFortress(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFortress(x uint64) (n int) {
	return sovFortress(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Fortress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFortress
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fortress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fortress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFortress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFortress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFortress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFortress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFortress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFortress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFortress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFortress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFortress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFortress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Collateral = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deadline", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFortress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFortress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFortress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deadline = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFortress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFortress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFortress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFortress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFortress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFortress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Borrower = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFortress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFortress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFortress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFortress(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFortress
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFortress(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFortress
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFortress
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFortress
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFortress
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFortress
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFortress
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFortress        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFortress          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFortress = fmt.Errorf("proto: unexpected end of group")
)
